### ISSUE TITLE
sort series

### ISSUE THREAD

**Issue by skydiver** [PascalKleindienst/october-blogseries-extension#2]
would be nice to have some kind of custom sorting on "blogSeriesList" component

right now, my series are years (2016, 2015, 2014...) and i want to sort from higher to lower

thanks.-

**Comment by PascalKleindienst** [comment]
Hi,

I've now implemented a sorting option for both components for attributes like Title, Created, Updated _(like to Rainlab.BlogPost options)_ :smiley: 

Regards,
Pascal
